var paisArray = ["Afghanistan", "Albania", "Argélia", "Samoa Americana", "Andorra", "Angola", "Anguilla", "Antarctica",
"Antígua e Barbuda", "Argentina", "Arménia", "Aruba", "Austrália", "Áustria", "Azerbaijão", "Bahamas", "Bahrein", "Bangladesh",
"Barbados", "Bielorrússia", "Bélgica", "Belize", "Benin", "Bermuda", "Butão", "Bolívia", "Bósnia e Herzegovina", "Botsuana",
"Ilha Bouvet", "Brasil", "Brunei", "Bulgária", "Burquina Faso", "Burundi", "Camboja", "Camarões", "Canadá", "Cabo Verde", 
"Ilhas Caiman", "República Centro-Africana", "Chade", "Chile", "China", "Ilha Christmas", "Colômbia", "Comores", "Congo", "Congo",
"Ilhas Cook", "Costa Rica", "Costa do Marfim", "Croácia", "Cuba", "Chipre", "República Checa", "Dinamarca", "Djibouti",
"Dominica", "República Dominicana", "Timor Leste", "Equador", "Egipto", "El Salvador", "Guiné Equatorial", "Eritreia", "Estónia",
"Etiópia", "Ilhas Malvinas", "Ilhas Faroé", "Fiji", "Finlândia", "França", "França Metropolitana", "Guiana Francesa",
"Polinésia Francesa", "Gabão", "Gâmbia", "Geórgia", "Alemanha", "Gana", "Gibraltar", "Grécia", "Gronelândia", "Granada", "Guadalupe", 
"Guam", "Guatemala", "Guiné", "Guiné-Bissau", "Guiana", "Haiti", "Ilhas Heard e Mc Donald", "Vaticano", 
"Honduras", "Hong Kong", "Hungria", "Islândia", "Índia", "Indonésia", "Irã", "Iraque", "Irlanda", "Israel", "Itália", "Jamaica", 
"Japão", "Jordânia", "Cazaquistão", "Quênia", "Kiribati", "Coréia do Norte", "Coréia do Sul", "Kuwait", "Quirguizistão", "Laos", 
"Letónia", "Líbano", "Lesoto", "Libéria", "Líbia", "Liechtenstein", "Lituânia", "Luxemburgo", "Macau", "Macedónia", "Madagáscar", 
"Malawi", "Malásia", "Maldivas", "Mali", "Malta", "Ilhas Marshall", "Martinica", "Mauritânia", "Maurícia", "Mayotte", "México", 
"Micronésia", "Moldávia", "Mónaco", "Mongólia", "Marrocos", "Moçambique", "Myanmar", "Namíbia", "Nauru", "Nepal", "Países Baixos",
"Nova Caledónia", "Nova Zelândia", "Nicarágua", "Níger", "Nigéria", "Niue", "Ilha Norfolk", "Ilhas Marianas do Norte", "Noruega",
"Omã", "Paquistão", "Palau", "Panamá", "Papua Nova Guiné", "Paraguai", "Peru", "Filipinas", "Polónia", "Portugal",
"Porto Rico", "Catar", "Reunião", "Roménia", "Federação Russa", "Ruanda", "São Cristóvão e Névis", "Santa Lúcia",
"São Vicente e Granadinas", "Samoa", "São Marino", "São Tomé e Príncipe", "Arábia Saudita", "Senegal", "Seychelles",
"Serra Leoa", "Singapura", "Eslováquia", "Eslovénia", "Ilhas Salomão", "Somália", "África do Sul",
"Ilhas Geórgia do Sul e Sandwich do Sul", "Espanha", "Sri Lanka", "Santa Helena", "São Pedro e Miquelon", "Sudão",
"Suriname", "Suazilândia", "Suécia", "Suíça", "Síria", "Taiwan", "Tajiquistão", "Tanzânia", "Tailândia", "Togo", "Tokelau", "Tonga",
"Trindade e Tobago", "Tunísia", "Turquia", "Turquemenistão", "Ilhas Turks e Caicos", "Tuvalu", "Uganda", "Ucrânia",
"Emirados Árabes Unidos", "Reino Unido", "Estados Unidos", "Uruguai", "Usbequistão", "Vanuatu", "Venezuela", "Vietname", 
"Saara Ocidental", "Iémen", "Zâmbia", "Zimbabué"];

var capitalArray = ["Abu Dhabi", "Abuja", "Acra", "Adamstown", "Adis Abeba", "Argel", "Alofi", "Amã", "Amesterdão", "Ancara", "Antananarivo", "Apia",
"Ashgabat", "Asmara", "Assunção", "Atenas", "Avarua", "Bagdá", "Baku", "Bamako", "Bandar Seri Begawan", "Banguecoque", "Bangui",
"Banjul", "Basseterre", "Beijing", "Beirute", "Belgrado", "Belmopan", "Berlim", "Berna", "Bishkek", "Bissau", "Bogotá", "Brasília",
"Bratislava", "Bridgetown", "Bruxelas", "Bucareste", "Budapeste", "Buenos Aires", "Cairo", "Camberra", "Caracas", "Conakry", "Copenhagem",
"Dakar", "Damasco", "Dhaka", "Dili", "Djibouti", "Dodoma", "Doha", "Dublim", "Dushanbe"];